FIX - Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
        at jmri.enginedriver.ImageDownloader.downloadBitmap(ImageDownloader.java:166)
        at jmri.enginedriver.ImageDownloader$BitmapDownloaderTask.doInBackground(ImageDownloader.java:250)
        at jmri.enginedriver.ImageDownloader$BitmapDownloaderTask.doInBackground(ImageDownloader.java:236)